basic back server
go-park-mail-ru/2021_1_Fyvaoldzh pull request #1
Opened 2021-03-03 21:32 UTC by MeHighLove

2021-03-04 09:52 UTC, OlegElizarov requested changes

2021-03-04 09:52 UTC, OlegElizarov commented on server.go
> +import (
Отсортировать импорты

2021-03-04 09:52 UTC, OlegElizarov commented on server.go
> +	Name string `json: "name"`
Убрать пробел между : и "

2021-03-04 09:52 UTC, OlegElizarov commented on server.go
> +func getIvent(c echo.Context) error {
Event =)

2021-03-04 09:52 UTC, OlegElizarov commented on server.go
> +	err := c.Bind(u)
В целом этот метод рабочий, но более верным является чтение тела запроса в отдельную переменную, а потом использование Маршаллов для конвертации слайса байт в значения твоей структуры

2021-03-04 09:52 UTC, OlegElizarov commented on server.go
> +		panic(err)
Никаких паник! Это в Го очень не любят. Простого log.Println(err) пока что достаточно

2021-03-04 09:52 UTC, OlegElizarov commented on server.go
> +	return c.JSON(http.StatusCreated, u.Name + u.Email)
Лучше в response.Writer писать Джейсон версию твоей модельки

2021-03-04 09:52 UTC, OlegElizarov commented on server.go
> +	name := c.FormValue("name")
Данные считывать как Джейсон(application/json).То есть из боди запроса маршалить в твои структуры

2021-03-04 09:52 UTC, OlegElizarov commented on server.go
> + 	dst, err := os.Create(img.Filename)
Вроде как ты просто создаешь пустой файлик с тем же именем, что и файлик на вход.Контента в твое файлик не будет

2021-03-04 09:52 UTC, OlegElizarov commented on server.go
> +	e.GET("/users", userJson)
Если ты хочешь взаимодействовать с телом запроса , то лучше сделать этот с запросом с методом POST

2021-03-04 09:52 UTC, OlegElizarov commented on server.go
> +package main
Лучше сделать файлик main.go , в котором будут вызывать методы из другого файла, например server.go, которые создадут сервер и запустят его.То есть реализации в файле main быть не должно

2021-03-06 13:20 UTC, MeHighLove commented on server.go
> +	return c.JSON(http.StatusCreated, u.Name + u.Email)
вот здесь не совсем понял, что именно надо исправить. Можно как-то переформулировать?

2021-04-17 12:33 UTC, merged